# Generated by Django 4.2 on 2025-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='tiffin_price',
            field=models.DecimalField(decimal_places=2, default='120', max_digits=6),
        ),
    ]
