# Generated by Django 4.2 on 2025-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_track_tiffin_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='eat_by',
            new_name='eat_by_persons',
        ),
    ]
