# Generated by Django 4.2 on 2025-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_rename_eat_by_track_eat_by_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='eat_by_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
