# Generated by Django 4.2 on 2025-04-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_track_eat_by_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='eat_by_persons',
            new_name='eat_by',
        ),
    ]
