# Generated by Django 4.2.10 on 2025-04-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Tracker", "0005_rename_eat_by_persons_track_eat_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="track",
            name="chirag_wallet",
        ),
        migrations.RemoveField(
            model_name="track",
            name="dev_wallet",
        ),
        migrations.RemoveField(
            model_name="track",
            name="dhruv_wallet",
        ),
        migrations.RemoveField(
            model_name="track",
            name="eat_by_count",
        ),
        migrations.RemoveField(
            model_name="track",
            name="manan_wallet",
        ),
        migrations.RemoveField(
            model_name="track",
            name="manto_wallet",
        ),
        migrations.RemoveField(
            model_name="track",
            name="per_person_price",
        ),
        migrations.RemoveField(
            model_name="track",
            name="pratik_wallet",
        ),
        migrations.RemoveField(
            model_name="track",
            name="weekday",
        ),
        migrations.RemoveField(
            model_name="track",
            name="eat_by",
        ),
        migrations.AlterField(
            model_name="track",
            name="tiffin_price",
            field=models.DecimalField(decimal_places=2, default=120, max_digits=6),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Tracker.member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="track",
            name="eat_by",
            field=models.ManyToManyField(related_name="tiffins", to="Tracker.member"),
        ),
    ]
