# Generated by Django 4.2.10 on 2025-04-09 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Tracker", "0006_member_remove_track_chirag_wallet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="balance",
            new_name="total_amount",
        ),
    ]
