# Generated by Django 5.1.4 on 2025-01-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lift_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lift_data",
            name="current_floor",
            field=models.IntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="lift_data",
            name="target_floor",
            field=models.IntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                ]
            ),
        ),
    ]
